language: generic
sudo: required
dist: trusty
env:
  global:
  - secure: De+K0aDRyqTJLm4D6HZK3KD72EVToyWRFisG3KjqAHUuWcRwNgdmmO35fs8QQramsNGHgLrnyEznGZdPhyKavB50x4cG4hYFyyqeWP7i8K+IYvyA9juVDXI3oTXlF4pPfk5n95vRvJDdgTEuPYIFa+p7HpLfxweTo2j7BQRCiL7h7+Li8kuvLnpD9iG3lgc/Y0XHDe+1KECW2+rCMe+wcUbmUliXyRUv3QrzzUYr4PiZAiV8gHQxBdK1pGSumne8+7LCXXjURyWp/tSBKwGDcpBeZ3k6XlPXh0n7k5RXlm8YYj6gpAExliFyIlrG8EGqkmBWENmJO/kr6qLgF6+K1YJAlihs0wXRJPjUPmWSSyNIaSIviM1d2LXCxb25XyypV+TtXuw9lzdwqJcpFpi7BCYy8FC7hFZaawJSgQ3VNm8PKzJKE9LKr4zMnLMbO4588CJvF57ySEso/US6TSRUcXXC02l9FirWB3vv1EXrVeomzY9wkS8ka0IhPGUta/5WigXj9sEpn2uKuTMa8ZvENe8hmbu6G3/3btUmthSBHdfG7ghVupDoZ19X6pIsM/igPM0VHkP//XbdfjsJkfSMk5Zyrw2CGFrri11cXRZsJNOTj2o4s0ez8PK5A1WQkn5a11+7RVFQ131UbtcmDzobKwEwhWgFT9epd5RbOFP7rzA=
  - secure: VHP9dIZyaOzKrx0DfwX4zePrs6WGuIL8hNlM5I7qmMiMVKUQaUbHyFfrkkxeLydW3WbMxqYLBwDznHOBauJiMWTLKWaCrDEoo4ZuxTOYwHZnQH6mC4uH4bnJYIc/S5cFoTlT9puBleA+NO0L0LYbHhh+rvxR/X1/aRhO3JO9Gr/28SLh3fIPsI/y4CC2slF6dFW9BNjdoiCDWPfCQDvNxPDsu1q1fH/hRms1dcmyBnECIVr8ZRqMtFU9bDkkyYpX7iievdmN0nPHHfGcy2zoTMn1wuUYYc1PF8DKoLm5y+5EI/w0ccYNud6ZAoWlzN+5wYSgy6zF8YNVqm8/dBjfwfRJt9fSRBlBGGm89S7IWoYkM1nsmmZ3xDaW89mAAPvdz9++NkUbfLjJR8Us5PYF1prZfxmqwDlQHpfqA90hWnXQZAOWzFKLF6wCQKwQEFK02Tm16o1uJzA2qNzy7dHy2pTXhDMP86NYSzSXJd/7UrFpCLAr5Ct430TfEO4fF7iE3i8n3BgjtX7LZZ9Lqk/u9eu3iyD5IMWfeqMIPS0n0wDkNorKocANhIYfJx0EvtBmvVYSVLrhGk4ViJOBTrdnueXrxLsV4WKkRY9AAPTf/GmssW0hxWknDYA6d5WK/WMn0RrtxBlprjOc7wN5yNhvDkDHoCUcWcNqfD8w5myWQeA=
services:
- docker
before_script:
- printenv | awk -F= '{if ($1 ~ /^(TRAVIS|GITHUB)/) print $1"="$2}' > .env
- docker-compose build
- docker-compose run web composer install
script:
- docker-compose run web typesafety --verbose --review
- docker-compose run web composer test
matrix:
  fast_finish: true
notifications:
  email: false
