language: generic
sudo: required
dist: trusty
group: edge
env:
  matrix:
    secure: kHSwUtjqnm31SyMyM8AcG2IEBoGqfE9fqbVxRD7t8hocJkRLMgYYC+hz9UfEoubN/ClDycF3jnEKvUsIK3nmT+u41C0+8ZrjfVPF2ywm98u6cC6JlCFjdc3Wbi3DBsrcZmBSIWkVCOyLl+y8iC8/vT74/z3I5jiH8whmxNc9QZfj4CEsg19KII/1ujdlvdytbbMo2YHhcG1oaUj8KurDtMowbLwfIla78WPiB3pHB7FAw00KolxuESOfoblntWMkBx5nOrOhaBrm5QWpqrcRI5+3EGqWOWjgTZr3tjhtX0PFWW1DQV8mFgX3R9m4OLGIX0NdQ/uJlBf/Yhsg1bFmimg9iztYwhXfspOaSEtnznFpcSCfuf6CgIbfDd6cL6ZBdDxXRYe/YIT30zNKSv8m5OUIG9WP9PF5RX9iQT+QizsQbW8A5AaNAA19HYB06yLZTb0MN8zg+svbYvhx5DAxDuScGq1yHKiFTriuemjHPRxnQ6Jeh+uPhYyGdCmTy6ReJkA7KtXULUGob+U9z57TBlYS5B/JUsxDlfwJogGvghI1huUV70qr5KphK3VjEDP3gWSA4SFnG1IDTp47Kp8jLl3WLff2VQ+JYuQjzuvDg03XwXHE5KZXDP4ngalDwfvJiXZZ5iimIc73WOjB3stV3D0zk8JwVxCsD9w7/phgSbo=
services:
- docker
before_script:
- printenv | awk -F= '{if ($1 ~ /^(TRAVIS|GITHUB)/) print $1"="$2}' > .env
- docker-compose build
script:
- docker-compose run web typesafety --verbose --review
- docker-compose run web composer test
matrix:
  fast_finish: true
notifications:
  email: false
