language: generic
sudo: required
dist: trusty
services:
  - docker
before_install:
  - docker-compose run web composer install --no-interaction
  - docker-compose run web touch .hhconfig
script:
  - docker-compose run web hh_client restart
  - docker-compose run web hh_client check
  - docker-compose run web composer test
matrix:
  fast_finish: true
notifications:
  email: false
