version: '2'
services:
  web:
    image: typesafety/typesafety:latest
    working_dir: "/tmp/project"
    volumes:
      - .:/tmp/project
    tty: true
    cap_add:
      - ALL
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
