version: '2'
services:
  web:
    image: typesafety/typesafety:latest
    volumes:
      - ./:/home/develop/project
    tty: true
    cap_add:
      - ALL
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
